name: Deploy to GitHub Pages

on:
  push:
    branches: [ "tutorial-host" ]
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: "${{ steps.deployment.outputs.page_url }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências e buildar o Vue
        env:
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
        run: |
          cd app
          npm install
          npm run build

      - name: Organizar arquivos para o Deploy
        run: |
          mkdir _site
          cp index.html _site/
          cp style.css _site/
          cp -r images _site/
          mkdir -p _site/app/dist
          cp -r app/dist/* _site/app/dist/

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload dos arquivos compilados
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'

      - name: Deploy definitivo no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4